name: Run DPC Pipeline CUM24

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 02:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  run-dpc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout repository code

      - name: Setup R
        uses: r-lib/actions/setup-r@v2  # Set up R environment

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev libproj-dev libgeos-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("httr","jsonlite","terra","lubridate","googledrive","base64enc","stringr"))'

      - name: Run download script
        run: Rscript download_cum24.r


      - name: Upload aggregated files to Google Drive
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
        run: Rscript upload_to_drive3.r

