name: Meteo Daily Workflow

on:
  schedule:
    - cron: "0 4 * * *"  # 05:00 CET
  workflow_dispatch:

jobs:
  run-meteo:
    runs-on: ubuntu-latest

    env:
      GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}
      GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            httr
            jsonlite
            dplyr
            lubridate
            googledrive

      - name: Run meteo script
        run: Rscript meteo_script.R
        
      - name: Upload results to Drive
        run: Rscript upload_to_drive2.r
        
