name: Meteo Daily Workflow

on:
  schedule:
    - cron: "0 4 * * *"  # 05:00 CET
  workflow_dispatch:

jobs:
  run-meteo:
    runs-on: ubuntu-latest

    env:
      GDRIVE_OAUTH_JSON: ${{ secrets.GDRIVE_OAUTH_JSON }}
      GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            httr
            jsonlite
            dplyr
            lubridate
            googledrive

      - name: Run Meteo Script
        run: Rscript meteo_script.R

      - name: Upload CSV to Google Drive
        run: Rscript upload_to_drive2.r
